###################### Heartbeat Configuration #######################

http.enabled: true
http.port: ${MONITOR_PORT}
http.host: "0.0.0.0"

monitoring:
  enabled: false
  cluster_uuid: "${CLUSTER_UUID}"

heartbeat.config.monitors:
  # Directory + glob pattern to search for configuration files
  path: ${path.config}/monitors.d/*.yml
  # If enabled, heartbeat will periodically check the config.monitors path for changes
  reload.enabled: false
  # How often to check for changes
  reload.period: 5s

processors:
  # https://www.elastic.co/guide/en/beats/heartbeat/current/add-observer-metadata.html
  - add_observer_metadata:
      cache.ttl: 5m
      geo:
        name: KnO
        location: 50.3871, -13.17379
        continent_name: Europe
        country_iso_code: CZE
        region_name: Czech Republic
        region_iso_code: CZ-422
        city_name: Klášterec nad Ohří
  - add_tags:
      tags: ["${STAGE}"]
      target: "environment"
  - add_tags:
      tags: ["${APP_HOST}-${APP_ID}"]
      target: "app.id"

instrumentation:
  enabled: true
  environment: "${STAGE}"
  hosts: ["${ELASTIC_APM_SERVER_URL}"]
  # api_key: "${ELASTIC_APM_API_KEY}"
  tags: ["${APP_HOST}-${APP_ID}"]

heartbeat.monitors:

# - type: http
#   schedule: '*/15 * * * * *'
#   id: http-service-ext
#   name: HTTP Service
#   data_stream.namespace: default
#   service.name: heartbeat-http-ext
#   check.response.status: [200, 301, 401, 404]
#   tags: [web-ext]
#   hosts:
#     # eliasondrej.com
#     - https://eliasondrej.com
#     - https://traefik.eliasondrej.com
#     - https://kibana.eliasondrej.com
#   ssl:
#     verification_mode: "none"
 
- type: http
  # schedule: '*/30 * * * * * *'
  schedule: '* * * * * *'
  id: http-service
  name: HTTP Service
  data_stream.namespace: default
  service.name: heartbeat-http
  username: '${ELASTICSEARCH_USERNAME}'
  password: '${ELASTICSEARCH_PASSWORD}'
  # api_key: ${AGENT_API_KEY}
  check.response.status: [200]
  tags: [web]
  hosts:
    # ELK
    - http://cerebro.${APP_HOST}.${APP_NET}:9000
    - https://es01.${APP_HOST}.${APP_NET}:${ES1_PORT}
    - https://es02.${APP_HOST}.${APP_NET}:${ES2_PORT}
    # - https://es03.${APP_HOST}.${APP_NET}:${ES3_PORT}
    - https://${APP_HOST}.${APP_NET}/downloads/
    - https://wiki.${APP_HOST}.${APP_NET}/doku.php?id=wiki:welcome
    - http://heartbeat.${APP_HOST}.${APP_NET}:${MONITOR_PORT}
    - http://filebeat.${APP_HOST}.${APP_NET}:${MONITOR_PORT}
    - http://metricbeat.${APP_HOST}.${APP_NET}:${MONITOR_PORT}
    - https://cerebro.www.${APP_NET}
    - https://www.${APP_NET}/downloads/
    - https://wiki.www.${APP_NET}/doku.php?id=wiki:welcome
    - http://filebeat.www.${APP_NET}:${MONITOR_PORT}
    - http://metricbeat.www.${APP_NET}:${MONITOR_PORT}
    # traefik
    - http://filebeat.web.traefik.local:${MONITOR_PORT}
    - http://metricbeat.web.traefik.local:${MONITOR_PORT}
    - http://filebeat.www.traefik.local:${MONITOR_PORT}
    - http://metricbeat.www.traefik.local:${MONITOR_PORT}
    - http://logstash.www.traefik.local:${LOGSTASH_MONITOR_PORT}
    # logstash for finger print:
    # - https://logstash.${APP_HOST}.${APP_NET}:${LOGSTASH_PORT_5044}
    # tomcat
    - https://${APP_HOST}.tomcat.local/tombola-javadoc/
    - https://${APP_HOST}.tomcat.local/tomcat.jsp
    - https://ad.${APP_HOST}.tomcat.local
    - http://filebeat.${APP_HOST}.tomcat.local:${MONITOR_PORT}
    - http://metricbeat.${APP_HOST}.tomcat.local:${MONITOR_PORT}
    - https://www.tomcat.local/tombola-javadoc/
    - https://www.tomcat.local/tomcat.jsp
    - https://ad.www.tomcat.local
    - http://filebeat.${APP_HOST}.tomcat.local:${MONITOR_PORT}
    - http://metricbeat.${APP_HOST}.tomcat.local:${MONITOR_PORT}
    - http://filebeat.www.tomcat.local:${MONITOR_PORT}
    - http://metricbeat.www.tomcat.local:${MONITOR_PORT}
    # wordpress
    - https://${APP_HOST}.wordpress.local
    - https://pma.${APP_HOST}.wordpress.local
    - http://filebeat.${APP_HOST}.wordpress.local:${MONITOR_PORT}
    - http://metricbeat.${APP_HOST}.wordpress.local:${MONITOR_PORT}
    - https://www.wordpress.local
    - https://pma.www.wordpress.local
    - http://filebeat.www.wordpress.local:${MONITOR_PORT}
    - http://metricbeat.www.wordpress.local:${MONITOR_PORT}
    # intranet
    # - https://lhs.intranet.local/downloads/
    # - https://www.intranet.local/downloads/
  ssl:
    certificate_authorities: ['${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}']
    # verification_mode: "none"
    verification_mode: "${VERIFICATION_MODE}"

- type: tcp
#   schedule: '*/30 * * * * * *'
  schedule: '* * * * * *'
  id: tcp-service
  name: TCP Service
  data_stream.namespace: default
  service.name: heartbeat-tcp
  tags: [tcp]
  hosts:
    # - platypus-box_traefik_1.platypus-local-dev-network:80
    # - heartbeat.${APP_HOST}.${APP_NET}:${MONITOR_PORT}
    # - metricbeat.${APP_HOST}.${APP_NET}:${MONITOR_PORT}
    # - filebeat.${APP_HOST}.${APP_NET}:${MONITOR_PORT}
    # - eps.${APP_NET}:${ENTERPRISE_SEARCH_PORT}
    - kibana.${APP_HOST}.${APP_NET}:${KIBANA_PORT}
    # - logstash.${APP_HOST}.${APP_NET}:${LOGSTASH_MONITOR_PORT}
    # traefik
    # - filebeat.web.traefik.local:${MONITOR_PORT}
    # - metricbeat.web.traefik.local:${MONITOR_PORT}
    # - filebeat.www.traefik.local:${MONITOR_PORT}
    # - metricbeat.www.traefik.local:${MONITOR_PORT}
    # tomcat
    # - filebeat.${APP_HOST}.tomcat.local:${MONITOR_PORT}
    # - metricbeat.${APP_HOST}.tomcat.local:${MONITOR_PORT}
    # - filebeat.www.tomcat.local:${MONITOR_PORT}
    # - metricbeat.www.tomcat.local:${MONITOR_PORT}
    # wordpress
    # - filebeat.${APP_HOST}.wordpress.local:${MONITOR_PORT}
    # - metricbeat.${APP_HOST}.wordpress.local:${MONITOR_PORT}
    # - filebeat.www.tomcat.local:${MONITOR_PORT}
    # - metricbeat.www.tomcat.local:${MONITOR_PORT}

- type: icmp
  schedule: '*/30 * * * * * *'
#   schedule: '* * * * * *'
  id: icmp-service
  name: ICMP Service
  data_stream.namespace: default
  service.name: heartbeat-icmp
  tags: [icmp]
  hosts:
    - ${APP_HOST}.${APP_NET}
    - weblhs-php.${APP_NET}
    # - www.intranet.local
    # - apm.${APP_HOST}.${APP_NET}
    # - cerebro.${APP_HOST}.${APP_NET}
    # - es01.${APP_HOST}.${APP_NET}
    # - es02.${APP_HOST}.${APP_NET}
    # - es03.${APP_HOST}.${APP_NET}
    # - heartbeat.${APP_NET}
    # - kibana.${APP_HOST}.${APP_NET}
    # - logstash.${APP_HOST}.${APP_NET}
    # - wiki.${APP_HOST}.${APP_NET}

heartbeat.scheduler:
  limit: 2
heartbeat.jobs:
  http:
    limit: 3
  browser:
    limit: 2    

output:

# ------------------------------ Elasticsearch Output -------------------------------
  elasticsearch:
    hosts: [ "https://es01.${HOST_NICK}.${APP_NET}:${ES1_PORT}" ]
    protocol: "https"
    username: '${ELASTICSEARCH_USERNAME}'
    password: '${ELASTICSEARCH_PASSWORD}'
    ssl:
      enabled: true
      certificate_authorities: ['${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}']
      verification_mode: "${VERIFICATION_MODE}"
