#
# === Elastic Agent as fleet server ===
#
# So that kibana doesn't complain that I have to make it :-) Elastic-agent is suitable for external systems.
# I don't want to lose metrics and logs on the main server because the agent won't connect.
#
  fleet:
    depends_on:
      es02:
        condition: service_healthy
    depends_on:
      kibana:
        condition: service_healthy
    depends_on:
      eps:
        condition: service_healthy
    # Ubuntu - fleet
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    # image: docker.elastic.co/beats/elastic-agent-complete:${STACK_VERSION} # ;-)
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      # for traefik:
      - default
      # local network:
      - intnet
    # ports:
    #  - ${FLEET_PORT}:8220
    container_name: "${APP_ID}-fleet"
    hostname: "fleet.${INT_NETWORK}"
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./certs:/usr/share/elastic-agent/certs
      - ./extras/elastic-agent/elastic-agent.yml:/usr/share/elastic-agent/elastic-agent.yml
      - ./extras/elastic-agent/apm-server.yml:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/apm-server-${STACK_VERSION}-linux-x86_64/apm-server.yml
      - ./extras/elastic-agent/fleet-server.yml:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/fleet-server-${STACK_VERSION}-linux-x86_64/fleet-server.yml
      - ./extras/elastic-agent/filebeat.yml:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/filebeat.yml
      - ./extras/elastic-agent/metricbeat.yml:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/metricbeat-${STACK_VERSION}-linux-x86_64/metricbeat.yml
      - ./extras/elastic-agent/heartbeat.yml:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/heartbeat-${STACK_VERSION}-linux-x86_64/heartbeat.yml
      - ./logs/fleet/elastic-agent:/usr/share/elastic-agent/state/data/logs
      - ./logs/fleet/apm-server:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/apm-server-${STACK_VERSION}-linux-x86_64/logs
      - ./logs/fleet/filebeat:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/logs
      - ./logs/fleet/heartbeat:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/heartbeat-${STACK_VERSION}-linux-x86_64/logs
      - ./logs/fleet/metricbeat:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/metricbeat-${STACK_VERSION}-linux-x86_64/logs
      - ./logs/apm:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/apm-server
      - ./logs/es01:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/es01
      - ./logs/es02:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/es02
      - ./logs/es03:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/es03
      - ./logs/dokuwiki:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/dokuwiki
      - ./logs/eps:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/eps
      - ./logs/file/logs:/usr/share/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/file/logs
      - ./logs/file/filebeat:/usr/share/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/file/data/registry/filebeat
      - ./logs/heart:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/heart
      - ./logs/kibana:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/kibana
      - ./logs/nginx:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/default
      - ./logs/metric:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/metric
      - /root/platypus-wordpress-mysql/logs/wordpress-nginx/:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/platypus-wordpress-mysql
      - /root/tombola/logs/tombola-nginx/:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/tombola
      - /root/tombola/logs/tombola-tomcat/:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/tomcat/tombola
      - /root/platypus-box/logs/traefik:/usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/traefik
      - fleet:/usr/share/elastic-agent
    environment:
      - APP_ID=${APP_ID}
      - APP_HOST=${APP_HOST}
      - APP_NET=${INT_NETWORK}
      - APM_SERVER_CERT=/usr/share/apm-server/certs/apm.fleet.${INT_NETWORK}/apm.fleet.${INT_NETWORK}.crt
      - APM_SERVER_CERT_KEY=/usr/share/apm-server/certs/apm.fleet.${INT_NETWORK}/apm.fleet.${INT_NETWORK}.key
      - CLUSTER_NAME=${CLUSTER_NAME}
      - CLUSTER_UUID=${CLUSTER_UUID}
      - ELASTICSEARCH_HOSTS=https://es01.${APP_HOST}.${INT_NETWORK}:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${APM_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/elastic-agent/certs/ca/ca.crt
      # - ELASTICSEARCH_SERVICE_TOKEN=${ELASTICSEARCH_SERVICE_TOKEN}
      - FLEET_ENROLL=0
      - FLEET_SERVER_ENABLE=1
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://es01.${APP_HOST}.${INT_NETWORK}:9200
      - FLEET_SERVER_ELASTICSEARCH_USERNAME=elastic
      - FLEET_SERVER_ELASTICSEARCH_PASSWORD=${APM_PASSWORD}
      - FLEET_SERVER_ELASTICSEARCH_CA=/usr/share/elastic-agent/certs/ca/ca.crt
      - FLEET_SERVER_ELASTICSEARCH_REQUESTTIMEOUT=180000
      - FLEET_CA=/usr/share/elastic-agent/certs/ca/ca.crt
      - FLEET_SERVER_CERT=/usr/share/elastic-agent/certs/fleet.${INT_NETWORK}/fleet.${INT_NETWORK}.crt
      - FLEET_SERVER_CERT_KEY=/usr/share/elastic-agent/certs/fleet.${INT_NETWORK}/fleet.${INT_NETWORK}.key
      - FLEET_SERVER_POLICY_ID=${FLEET_SERVER_POLICY_ID}
      - FLEET_SERVER_SERVICE_TOKEN=${FLEET_SERVER_SERVICE_TOKEN}
      # - FLEET_ENROLLMENT_TOKEN=${FLEET_ENROLLMENT_TOKEN}
      - FLEET_URL=https://fleet.${INT_NETWORK}:8220
      - KIBANA_FLEET_USERNAME=elastic
      - KIBANA_FLEET_PASSWORD=${APM_PASSWORD}
      - KIBANA_FLEET_HOST=https://kibana.${APP_HOST}.${INT_NETWORK}:5601
      - KIBANA_FLEET_CA=/usr/share/elastic-agent/certs/ca/ca.crt
      - KIBANA_FLEET_SETUP=1
      - KIBANA_FLEET_REQUESTTIMEOUT=1200000
      - STACK_VERSION=${STACK_VERSION}
      - STV=${STV}
    healthcheck:
      test: ["CMD-SHELL", "elastic-agent status | grep 'Status: HEALTHY'"]
      # test: ["CMD-SHELL", "curl -s --cacert certs/ca/ca.crt -I https://fleet.${INT_NETWORK}:8220 | grep -q 'HTTP/2 404'"]
      interval: 30s
      timeout: 60s
      retries: 60
     
volumes:
  fleet:
    external: true
    name: "${APP_ID}-fleet"
