http.enabled: true
http.host: 0.0.0.0
http.port: 5066
#http.named_pipe.user:
#http.named_pipe.security_descriptor:

logging:
  to_stderr: true # Force the logging output to stderr
  level: trace

fleet:
  hosts: ["https://fleet.wordpress.local:8220"]
  # agent:
  #   id: "fb41b289-10cf-40c7-94fb-ee854e748e1e"

id: "${FLEET_SERVER_POLICY_ID}"
outputs:
  elasticsearch:
    hosts: ["https://es01.${APP_ID}.${APP_NET}:9200"]
    protocol: "https"
    username: "${ELASTICSEARCH_USERNAME}"
    password: "${ELASTICSEARCH_PASSWORD}"
    # service_token: '${FLEET_SERVER_SERVICE_TOKEN}'
    # api_key:  '${FLEET_ENROLLMENT_TOKEN}'

    ssl:
      enabled: true
      certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
      verification_mode: "${VERIFICATION_MODE}"
