# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: 
    - "http://metricbeat.${HOST_NICK}.${APP_NET}:5066"
    - "http://filebeat.${HOST_NICK}.${APP_NET}:5066"
    - "http://heartbeat.${HOST_NICK}.${APP_NET}:5066"
    - "http://apm-server.${HOST_NICK}.${APP_NET}:5066"
    - "http://filebeat.www.traefik.local:5066"
    - "http://metricbeat.www.traefik.local:5066"
  username: "beats_system"
  password: "${ELASTICSEARCH_PASSWORD}"
