# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: 
    - "http://metricbeat.${APP_HOST}.${APP_NET}:${MONITOR_PORT}"
    - "http://filebeat.${APP_HOST}.${APP_NET}:${MONITOR_PORT}"
    - "http://heartbeat.${APP_HOST}.${APP_NET}:${MONITOR_PORT}"
    # - "http://apm-server.${APP_HOST}.${APP_NET}:${MONITOR_PORT}"
  username: "beats_system"
  password: "${ELASTICSEARCH_PASSWORD}"
