# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: ["apm-server.${APP_HOST}.${APP_NET}:5066", "metricbeat.${APP_NET}:5066", "filebeat.${APP_NET}:5066", "heartbeat.${APP_NET}:5066"]
  username: "beats_system"
  #username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  # ssl:
  #  enabled: true
  #  certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
