# Module: enterprisesearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-enterprisesearch.html

- module: enterprisesearch
  xpack.enabled: true
  metricsets: ["health", "stats"]
  enabled: true
  period: 10s
  hosts: ["http://eps.${APP_HOST}.${APP_NET}:3002"]
  # hosts: ["http://eps.${APP_HOST}.${APP_NET}:3002/diagnostics"]
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  #username: "admin"
  #password: "${EPS_PASSWORD}"

  # ssl:
  #  enabled: true
  #  certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]

