# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-nginx.html

- module: nginx
  # metricsets:
  #  - stubstatus
  period: 10s

  # Nginx hosts
  hosts: 
    - "http://weblhs"
    # - "http://${APP_HOST}.${APP_NET}"

  # Path to server status. Default nginx_status
  server_status_path: "nginx_status"

  #ssl:
  #  enabled: true
  #  certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
