# Module: php_fpm
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.4/metricbeat-module-php_fpm.html

- module: php_fpm
  #metricsets:
  #  - pool
  #  - process
  period: 10s
  hosts: 
    - "https://${HOST_NICK}.${APP_NET}:443"
    - "https://wiki.${HOST_NICK}.${APP_NET}:443"
  status_path: "/status"
  ssl:
    enabled: true
    certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]

