# Module: php_fpm
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.4/metricbeat-module-php_fpm.html

- module: php_fpm
  # metricsets:
  #   - pool
  #   - process
  period: 10s
  hosts: 
    - "https://${APP_HOST}.${APP_NET}:443"
    - "https://wiki.${APP_HOST}.${APP_NET}:443"
  status_path: "/status"
  #username: "user"
  #password: "secret"
  ssl:
    enabled: true
    certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]

