version: '3.9'

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
  intnet:
    external: false
    name: ${INT_NETWORK}

volumes:
  postgres:
    external: true
    name: postgres-01
  redis01:
    external: true
    name: redis-01
  wordpress99:
    external: true
    name: wordpress-99
  wordpressdb99:
    external: true
    name: wordpress-db-99
  wordpresspma99:
    external: true
    name: wordpress-pma-99

services:
  # Alpine Linux
  weblhs:
    build:
      context: ./context
      dockerfile: Dockerfile 
    image: lhsradek/lhsdock:v3
    container_name: "${APP_ID}"
    hostname: "${APP_HOST}"
    restart: always
    # ports:
    #  - 4443:443
    volumes:
      - ./context/root/bin:/root/bin
      - ./application/html:/var/www/html:ro
      - ./extras/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./extras/nginx/pki/${CERTNAME}.pem:/etc/ssl/private/cacert.pem:ro
      - ./extras/nginx/pki/${CERTNAME}-key.pem:/etc/ssl/private/cacert-key.pem:ro
      - postgres:/root/bin/volume/postgres-01:ro
      - redis01:/root/bin/volume/redis-01:ro
      - wordpress99:/root/bin/volume/wordpress-99:ro
      - wordpressdb99:/root/bin/volume/wordpresssb-09:ro
      - wordpresspma99:/root/bin/volume/wordpress-pma-09:ro
    networks:
      - default
      - intnet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-public.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-public.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-public.tls=true"
      # - "traefik.http.services.${APP_ID}.loadbalancer.server.scheme=https"
      # - "traefik.http.services.${APP_ID}.loadbalancer.server.port=443"

  weblhs-php:
    # Alpine Linux
    image: php:fpm-alpine
    container_name: "${APP_ID}-php"
    hostname: "lhsdock-php.${INT_NETWORK}"
    restart: always
    volumes:
      - ./context/root/bin:/root/bin
      - ./application/html:/var/www/html:ro
    networks:
      - intnet
