version: '3.9'

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}

volumes:
  mysql:
    external: true
    name: mysql-01
  phpmyadmin:
    external: true
    name: phpmyadmin-01
  postgres:
    external: true
    name: postgres-01
  redis:
    external: true
    name: redis-01
  wordpress:
    external: true
    name: wordpress-01

services:
  nginx:
    build:
      context: ./context
      dockerfile: Dockerfile 
    image: nginx:alpine
    container_name: "${APP_ID}-webserver"
    restart: always
    # ports:
    #  - 9090:80
    volumes:
      - ./context/root/bin:/root/bin
      - ./application/html:/var/www/html:ro
      - ./extras/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - mysql:/root/bin/volume/mysql-01:ro
      - postgres:/root/bin/volume/postgres-01:ro
      - redis:/root/bin/volume/redis-01:ro
      - wordpress:/root/bin/volume/wordpress-01:ro
      - phpmyadmin:/root/bin/volume/phpmyadmin-01:ro
    environment:
      - NGINX_HOST=lhs.docker.local
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-public.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-public.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-public.tls=true"

    links:
      - php

  php:
    # Alpine Linux
    image: php:fpm-alpine
    container_name: "${APP_ID}-php"
    restart: always
    volumes:
      - ./context/root/bin:/root/bin
      - ./application/html:/var/www/html:ro
      - ./extras/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
