version: '3.9'

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}

volumes:
  mysql:
    external: true
    name: wordpress-db-99
  phpmyadmin01:
    external: true
    name: phpmyadmin-01
  phpmyadmin99:
    external: true
    name: phpmyadmin-99
  postgres:
    external: true
    name: postgres-01
  redis:
    external: true
    name: redis-01
  wordpress01:
    external: true
    name: wordpress-01
  wordpress99:
    external: true
    name: wordpress-99
  wordpresspma:
    external: true
    name: wordpress-pma-99

services:
  # Alpine Linux
  nginx:
    build:
      context: ./context
      dockerfile: Dockerfile 
    image: lhsradek/lhsdock:v3
    container_name: "${APP_ID}"
    hostname: "${APP_HOST}"
    restart: always
    # ports:
    #  - 80:80
    #  - 443:443
    volumes:
      - ./context/root/bin:/root/bin
      - ./application/html:/var/www/html:ro
      - ./extras/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - type: bind
        source: ./extras/nginx/pki/docker.traefik.local.pem
        target: /etc/ssl/private/docker.traefik.local.pem
        read_only: true
      - type: bind
        source: ./extras/nginx/pki/docker.traefik.local-key.pem
        target: /etc/ssl/private/docker.traefik.local-key.pem
        read_only: true
      - mysql:/root/bin/volume/mysql-01:ro
      - postgres:/root/bin/volume/postgres-01:ro
      - redis:/root/bin/volume/redis-01:ro
      - wordpress01:/root/bin/volume/wordpress-01:ro
      - wordpress99:/root/bin/volume/wordpress-99:ro
      - wordpresspma:/root/bin/volume/wordpress-pma-01:ro
      - phpmyadmin01:/root/bin/volume/phpmyadmin-01:ro
      - phpmyadmin99:/root/bin/volume/phpmyadmin-99:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-public.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-public.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-public.tls=true"
      # - "traefik.http.services.${APP_ID}.loadbalancer.server.port=443"
    links:
      - php

  php:
    # Alpine Linux
    image: php:fpm-alpine
    container_name: "${APP_ID}-php"
    hostname: "${APP_HOST}"
    restart: always
    volumes:
      - ./context/root/bin:/root/bin
      - ./application/html:/var/www/html:ro
