version: '3.9'

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}

volumes:
  postgres:
    external: true
    name: postgres-01
  redis:
    external: true
    name: redis-01
  wordpress99:
    external: true
    name: wordpress-99
  wordpressdb99:
    external: true
    name: wordpress-db-99
  wordpresspma99:
    external: true
    name: wordpress-pma-99

services:
  # Alpine Linux
  nginx:
    build:
      context: ./context
      dockerfile: Dockerfile 
    image: lhsradek/lhsdock:v3
    container_name: "${APP_ID}"
    hostname: "${APP_HOST}"
    restart: always
    # ports:
    #  - 4443:443
    volumes:
      - ./context/root/bin:/root/bin
      - ./application/html:/var/www/html:ro
      - type: bind
        source: ./extras/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./extras/nginx/pki/${CERTNAME}.pem
        target: /etc/ssl/private/cacert.pem
        read_only: true
      - type: bind
        source: ./extras/nginx/pki/${CERTNAME}-key.pem
        target: /etc/ssl/private/cacert-key.pem
        read_only: true
      - postgres:/root/bin/volume/postgres-01:ro
      - redis:/root/bin/volume/redis-01:ro
      - wordpress99:/root/bin/volume/wordpress-99:ro
      - wordpressdb99:/root/bin/volume/wordpresssb-09:ro
      - wordpresspma99:/root/bin/volume/wordpress-pma-01:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-public.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-public.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-public.tls=true"
      - "traefik.http.services.nginx-${APP_ID}.loadbalancer.server.scheme=https"
      - "traefik.http.services.nginx-${APP_ID}.loadbalancer.server.port=443"
    links:
      - php

  php:
    # Alpine Linux
    image: php:fpm-alpine
    container_name: "${APP_ID}-php"
    hostname: "${APP_HOST}"
    restart: always
    volumes:
      - ./context/root/bin:/root/bin
      - ./application/html:/var/www/html:ro
