version: '3.9'

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
  intnet:
    external: false
    name: ${INT_NETWORK}

services:
  # Alpine Linux
  weblhs:
    build:
      context: ./context
      dockerfile: Dockerfile 
    image: lhsradek/lhsdock:v3
    # image: nginx:alpine
    container_name: "${APP_ID}"
    hostname: "${APP_HOST}.${INT_NETWORK}"
    restart: ${DOCKER_RESTART_POLICY}
    # ports:
    # - 80:80
    # - 443:443
    volumes:
      # - /root/bin/alpine:/root/bin/alpine:ro
      # if http
      - ./extras/nginx/default-http.conf:/etc/nginx/conf.d/default.conf:ro
      # else if https
      # - ./extras/nginx/default-https.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./certs/${CERTNAME}.pem:/etc/ssl/private/cacert.pem:ro
      # - ./certs/${CERTNAME}-key.pem:/etc/ssl/private/cacert-key.pem:ro
      # fi
      - ./application/html:/var/www/html:ro
      - ./logs:/var/log/nginx
      - wordpresswp99:/root/bin/volume/wordpress-wp-99:ro
      - wordpressdb99:/root/bin/volume/wordpress-db-99:ro
      - wordpresspma99:/root/bin/volume/wordpress-pma-99:ro
      - wordpressredis99:/root/bin/volume/wordpress-redis-99:ro
      - tomboladb:/root/bin/volume/tombola-db:ro
    networks:
      - intnet
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.weblhs-public.rule=Host(`${APP_HOST}.${INT_NETWORK}`)"
      - "traefik.http.routers.weblhs-public.entrypoints=https"
      - "traefik.http.routers.weblhs-public.tls=true"
      # if https
      # - "traefik.http.services.weblhs-platypus-${APP_ID}.loadbalancer.server.scheme=https"
      # - "traefik.http.services.weblhs-platypus-${APP_ID}.loadbalancer.server.port=443"

  weblhs-php:
    # Alpine Linux
    image: php:fpm-alpine
    # image: lhsradek/fpm:v1
    container_name: "${APP_ID}-php"
    hostname: "weblhs-php.${INT_NETWORK}"
    restart: ${DOCKER_RESTART_POLICY}
    volumes:
      # - /root/bin/alpine:/root/bin/alpine:ro
      - ./application/html:/var/www/html:ro
      # - ./context/root/bin/alpine/add.sh:/root/bin/alpine/add2.sh:rw
    networks:
      - intnet

volumes:
  wordpresswp99:
    external: true
    name: wordpress-wp-99
  wordpressdb99:
    external: true
    name: wordpress-db-99
  wordpresspma99:
    external: true
    name: wordpress-pma-99
  wordpressredis99:
    external: true
    name: wordpress-redis-99
  tomboladb:
    external: true
    name: tombola-db
