version: '3.9'

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
  intnet:
    external: false
    name: ${INT_NETWORK}

volumes:
  postgres01:
    external: false
    name: postgres-01
  wordpresswp99:
    external: true
    name: wordpress-wp-99
  wordpressdb99:
    external: true
    name: wordpress-db-99
  wordpresspma99:
    external: true
    name: wordpress-pma-99
  wordpressredis99:
    external: true
    name: wordpress-redis-99

services:
  # Alpine Linux
  weblhs:
    build:
      context: ./context
      dockerfile: Dockerfile 
    image: lhsradek/lhsdock:v3
    container_name: "${APP_ID}"
    hostname: "${APP_HOST}"
    restart: ${DOCKER_RESTART_POLICY}
    # ports:
    # - 4443:443
    volumes:
      # - ./context/root/bin:/root/bin:rw
      - ./application/html:/var/www/html:ro
      - ./extras/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx
      - ./certs/${CERTNAME}.pem:/etc/ssl/private/cacert.pem:ro
      - ./certs/${CERTNAME}-key.pem:/etc/ssl/private/cacert-key.pem:ro
      # - postgres01:/root/bin/volume/postgres-01:ro
      # - redis01:/root/bin/volume/redis-01:ro
      - wordpresswp99:/root/bin/volume/wordpress-wp-99:ro
      - wordpressdb99:/root/bin/volume/wordpress-db-99:ro
      - wordpresspma99:/root/bin/volume/wordpress-pma-99:ro
      - wordpressredis99:/root/bin/volume/wordpress-redis-99:ro
    networks:
      - intnet
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-weblhs-public.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-weblhs-public.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-weblhs-public.tls=true"
      - "traefik.http.services.weblhs-platypus-${APP_ID}.loadbalancer.server.scheme=https"
      - "traefik.http.services.weblhs-platypus-${APP_ID}.loadbalancer.server.port=443"

  lhsdock:
    # Alpine Linux
    image: php:fpm-alpine
    container_name: "${APP_ID}-php"
    hostname: "${APP_ID}"
    restart: ${DOCKER_RESTART_POLICY}
    volumes:
      - ./application/html:/var/www/html:ro
    networks:
      - intnet
