# Kibana configuration for docker target

xpack:
  reporting:
    kibanaServer:
      hostname: "kibana"
    roles:
      enabled: false
    encryptionKey: 8de551ca1432f0dcf3ad2908472562b1
  security:
    encryptionKey: 363792db7b8cf9581c6cbdddbb8ff95f
  encryptedSavedObjects:
    encryptionKey: 97aa4816075f95e8d51bac9159574a19
  monitoring:
    enabled: true
    ui:
      ccs:
        enabled: true

monitoring:
  ui:
    container:
      elasticsearch:
        enabled: true

server:
  host: "0.0.0.0"
  shutdownTimeout: "5s"
  publicBaseUrl: "https://kibana.docker.nginx.local:5601"
  ssl:
    enabled: true
    certificate: "/usr/share/kibana/config/certs/kibana/kibana.crt"
    key: "/usr/share/kibana/config/certs/kibana/kibana.key"

elasticsearch:
  hosts: ["https://es01:9200", "https://es02:9200"]

enterpriseSearch:
  host: "http://eps:3002"
