# Kibana configuration for docker target

monitoring:
  ui:
    enabled: true
    container:
      elasticsearch:
        enabled: false
    ccs:
      enabled: false
  kibana:
    collection.enabled: false

xpack:
  reporting:
    kibanaServer:
      hostname: "kibana"
    roles:
      enabled: false
    encryptionKey: 8de551ca1432f0dcf3ad2908472562b1
  security:
    encryptionKey: 363792db7b8cf9581c6cbdddbb8ff95f
    session:
      idleTimeout: 24h
  encryptedSavedObjects:
    encryptionKey: 97aa4816075f95e8d51bac9159574a19
  task_manager:
    poll_interval: 4000
    max_workers: 3
  apm.serviceMapEnabled: false
  fleet:
    agents:
      fleet_server:
        hosts:
          - "https://fleet.${APP_HOST}.${APP_NET}:8220"
          - "https://fleet.www.wordpress.local:8220"
          - "https://fleet.${APP_HOST}.wordpress.local:8220"
          - "https://fleet.www.tomcat.local:8220"
          - "https://fleet.${APP_HOST}.tomcat.local:8220"
        # elasticsearch.hosts: ["https://es01.${APP_HOST}.${APP_NET}:9200"]

    # https://www.elastic.co/guide/en/fleet/current/create-a-policy-no-ui.html
    packages:
      - name: fleet_server
        version: latest
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: apm
        version: latest
      - name: docker
        version: latest
      - name: mysql
        version: latest
      - name: nginx
        version: latest
      - name: postgresql
        version: latest
      - name: redis
        version: latest
      - name: tomcat
        version: latest
      - name: traefik
        version: latest
      - name: linux
        version: latest
      - name: logstash
        version: latest
      - name: spring_boot
        version: latest

    # https://www.elastic.co/guide/en/kibana/current/fleet-settings-kb.html
    # https://www.elastic.co/guide/en/fleet/current/migrate-beats-to-agent.html
    agentPolicies:          
      - name: Fleet Server policy 1
        description: Fleet Server policy
        id: fleet-server-policy
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        package_policies:
          - name: fleet_server-1
            package:
              name: fleet_server
            description: Fleet Server
            id: fleet_server-1
            # https://www.elastic.co/guide/en/fleet/current/secure-connections.html
            # Advanced options - Custom fleet-server configurations
            # ssl.certificate_authorities: ["/usr/share/elastic-agent/certs/ca/ca.crt"]
          - name: elastic_agent-1
            package:
              name: elastic_agent
            description: Elastic Agent
            id: elastic_agent-1
          - name: apm-1
            package:
              name: apm
            description: Elastic APM
            id: apm-1
            inputs:
              - type: apm
                vars:
                  - name: host
                    value: "0.0.0.0:8200"
                  - name: url
                    value: "http://fleet.${APP_HOST}.${APP_NET}:8200"
          - name: docker-1
            package:
              name: docker
            description: Docker Metrics
            id: docker-1
          - name: system-1
            package:
              name: system
            description: System
            id: system-1
            inputs:
              - type: system/logs
                keep_enabled: true
                vars:
                  - name: auth.paths
                    value:
                      - /hostfs/var/log/auth.log
                      - /hostfs/var/log/secure
                  - name: syslog.paths
                    value:
                      - /hostfs/var/log/messages
                      - /hostfs/var/log/syslog
              - type: system/metrics
                keep_enabled: true
                vars:
                  - name: system.hostfs
                    value: /hostfs
          - name: nginx-1
            package:
              name: nginx
            description: Nginx
            id: nginx-1
            inputs:
              - type: nginx/logs
                keep_enabled: true
                vars:
                  - name: nginx-access.paths
                    value:
                      - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/default/access.log
                      - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/default/php-access.log
                      - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/dokuwiki/nginx/access.log
                      - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/dokuwiki/php/access.log
                  - name: nginx-error.paths
                    value:
                      - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/default/error.log
                      - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/default/php-error.log
                      - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/dokuwiki/nginx/error.log
                      - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/dokuwiki/php/error.log
              - type: nginx/metrics
                vars:
                  - name: hosts
                    value:
                      - http://${APP_HOST}.${APP_NET}:80 
                      - http://wiki.${APP_HOST}.${APP_NET}:80 
          - name: logstash-1
            package:
              name: logstash
            description: Logstash
            id: logstash-1
          - name: traefik-1
            package:
              name: traefik
            description: Traefik
            id: traefik-1
            # /usr/share/elastic-agent/data/elastic-agent-9da6ba/install/filebeat-8.5.0-linux-x86_64/elogs/traefik/access.json
             
#       - name: Fleet Server Wordpress policy 1
#         description: Fleet Server Wordpress policy
#         id: fleet-server-wordpress-policy-1
#         namespace: default
#         monitoring_enabled:
#           - logs
#           - metrics
#         package_policies:
#           - name: fleet_server_wordpress-1
#             description: Fleet Server
#             id: fleet_server_wordpress-1
#             package:
#               name: fleet_server
#           - name: elastic_agent_wordpress-1
#             description: Elastic Agent
#             id: elastic_agent_wordpress-1
#             package:
#               name: elastic_agent
#           - name: apm_wordpress-1
#             description: Elastic APM
#             id: apm_wordpress-1
#             package:
#               name: apm
#             inputs:
#               - type: apm
#                 vars:
#                   - name: host
#                     value: "0.0.0.0:8200"
#                   - name: url
#                     value: "http://fleet.${APP_HOST}.wordpress.local:8200"
#           - name: system_wordpress-1
#             description: System Integration
#             id: system_wordpress-1
#             package:
#               name: system
#             inputs:
#               - type: system/logs
#                 vars:
#                   - name: auth.paths
#                     value:
#                       - /hostfs/var/log/auth.log
#                       - /hostfs/var/log/secure
#                   - name: syslog.paths
#                     value:
#                       - /hostfs/var/log/messages
#                       - /hostfs/var/log/syslog
#               - type: system/metrics
#                 keep_enabled: true
#                 vars:
#                   - name: system.hostfs
#                     value: /hostfs
#           - name: nginx_wordpress-1
#             package:
#               name: nginx
#             description: Nginx
#             id: nginx_wordpress-1
#             inputs:
#               - type: nginx/logs
#                 vars:
#                   - name: nginx-access.paths
#                     value:
#                       - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/platypus-wordpress-mysql/access.log
#                       - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/platypus-wordpress-mysql/php-access.log
#                       - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/platypus-wordpress-mysql/pma.access.log
#                       - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/platypus-wordpress-mysql/wp.access.log
#                   - name: nginx-error.paths
#                     value:
#                       - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/platypus-wordpress-mysql/error.log
#                       - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/platypus-wordpress-mysql/php-error.log
#                       - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/platypus-wordpress-mysql/pma.error.log
#                       - /usr/share/elastic-agent/data/elastic-agent-${STV}/install/filebeat-${STACK_VERSION}-linux-x86_64/elogs/nginx/platypus-wordpress-mysql/wp.error.log
#               - type: nginx/metrics
#                 vars:
#                   - name: hosts
#                     value:
#                       - http://${APP_HOST}.wordpress.local:80 
              
#       - name: Fleet Server Tomcat policy 1
#         description: Fleet Server Tomcat policy
#         id: fleet-server-tomcat-policy-1
#         namespace: default
#         monitoring_enabled:
#           - logs
#           - metrics
#         package_policies:
#           - name: fleet_server_tomcat-1
#             description: Fleet Server
#             id: fleet_server_tomcat-1
#             package:
#               name: fleet_server
#           - name: elastic_agent_tomcat-1
#             description: Elastic Agent
#             id: elastic_agent_tomcat-1
#             package:
#               name: elastic_agent
#           - name: apm_tomcat-1
#             description: Elastic APM
#             id: apm_tomcat-1
#             package:
#               name: apm
#             inputs:
#               - type: apm
#                 keep_enabled: true
#                 vars:
#                   - name: host
#                     value: "0.0.0.0:8200"
#                   - name: url
#                     value: "http://fleet.${APP_HOST}.tomcat.local:8200"
#           - name: system_tomcat-1
#             description: System Integration
#             id: system_tomcat-1
#             package:
#               name: system
#             inputs:
#               - type: system/logs
#                 vars:
#                   - name: auth.paths
#                     value:
#                       - /hostfs/var/log/auth.log
#                       - /hostfs/var/log/secure
#                   - name: syslog.paths
#                     value:
#                       - /hostfs/var/log/messages
#                       - /hostfs/var/log/syslog
#               - type: system/metrics
#                 keep_enabled: true
#                 vars:
#                   - name: system.hostfs
#                     value: /hostfs
      
server:
  host: "0.0.0.0"
  shutdownTimeout: "5s"
  socketTimeout: "240000"
  publicBaseUrl: "https://kibana.${APP_HOST}.${APP_NET}:5601"
  ssl:
    enabled: true
    certificate: "${ELASTICSEARCH_SSL_SERVER_CERT}" 
    key: "${ELASTICSEARCH_SSL_SERVER_CERT_KEY}"

elasticsearch:
  hosts: 
    - "https://es01.${APP_HOST}.${APP_NET}:9200"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  requestTimeout: 240000

enterpriseSearch:
  host: "http://eps.${APP_NET}:3002"
  accessCheckTimeout: 30000

logging:
  appenders:
    file:
      type: file
      fileName: /usr/share/kibana/logs/kibana.log
      layout:
        type: pattern
        pattern: "[%date] [%level] [%logger] [%meta] %message"
  root:
    appenders: [default, file]
    level: info
  loggers:
    - name: plugins
      appenders: [default, file]
      level: info
    - name: optimize
      appenders: [default, file]
      level: info
    - name: telemetry
      appenders: [default, file]
      level: info
    - name: metrics.ops
      appenders: [default, file]
      level: info
