filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["https://es01:9200"]
  # hosts: ["https://es01:9200", "https://es02:9200"]
  username: "elastic"
  password: "changeme"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]
