######################### APM Server Configuration #########################

################################ APM Server ################################

apm-server:
  #host: "unix:///var/run/docker.sock"
  #host: "unix:/usr/share/elastic-agent/state/data/tmp/default/apm-server/apm-server.sock"
  host: "0.0.0.0"
  #host: "apm.nginx.local"

  #---------------------------- APM Server - RUM Real User Monitoring ----------------------------

  # Enable Real User Monitoring (RUM) Support. By default RUM is disabled.
  # RUM does not support token based authorization. Enabled RUM endpoints will not require any authorization
  # token configured for other endpoints.
  rum:
    enabled: false
    output:
      elasticsearch:
        hosts:
          - "https://es01.${APP_HOST}.${APP_NET}:9200"
          - "https://es02.${APP_HOST}.${APP_NET}:9201"
          # - "https://es03.${APP_HOST}.${APP_NET}:9202"
        protocol: "https"
        #api_key: "id:api_key"
        #api_key: "${AGENT_API_KEY}"
        username: "${ELASTICSEARCH_USERNAME}"
        password: "${ELASTICSEARCH_PASSWORD}"
        ssl.certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
        ssl.certificate: "${APM_SERVER_CERT}"
        ssl.key: "${APM_SERVER_CERT_KEY}"
      # Index pattern in which to search for source maps, when fetching source maps from Elasticsearch.
      index_pattern: "apm-*-sourcemap*"

  #---------------------------- APM Server - Agent Configuration ----------------------------
  kibana:
    enabled: true
    host: "https://kibana.${APP_HOST}.${APP_NET}:5601"
    protocol: "https"
    # api_key: "${AGENT_API_KEY}"
    # username: "apm_system"
    username: "${ELASTICSEARCH_USERNAME}"
    password: "${ELASTICSEARCH_PASSWORD}"
    ssl.enabled: true
    ssl.certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
    ssl.verification_mode: "certificate"
    ssl.certificate: "${APM_SERVER_CERT}"
    ssl.key: "${APM_SERVER_CERT_KEY}"

#================================ Outputs =================================

#output.console:


#-------------------------- Elasticsearch output --------------------------
id: apm-1
revision: 2
output.elasticsearch:
  enabled: true
  hosts: 
    - "https://es01.${APP_HOST}.${APP_NET}:9200"
    - "https://es02.${APP_HOST}.${APP_NET}:9201"
    # - "https://es03.${APP_HOST}.${APP_NET}:9202"
  protocol: "https"
  username: "apm_system"
  password: "${ELASTICSEARCH_PASSWORD}"
  ssl.enabled: true
  ssl.certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
  ssl.verification_mode: "certificate"
  ssl.certificate: "${APM_SERVER_CERT}"
  ssl.key: "${APM_SERVER_CERT_KEY}"
output_permissions:
  default:
    _elastic_agent_monitoring:
      indices:
        - names:
            - logs-elastic_agent.auditbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.cloudbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.elastic_agent-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.cloudbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.metricbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.heartbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.apm_server-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.auditbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.fleet_server-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.apm_server-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.filebeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.endpoint_security-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.osquerybeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.metricbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.heartbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.packetbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.osquerybeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.fleet_server-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.filebeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.endpoint_security-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.packetbeat-default
          privileges:
            - auto_configure
            - create_doc
    _elastic_agent_checks:
      cluster:
        - monitor
    apm:
      indices:
        - names:
            - logs-apm.app-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-apm.app.*-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-apm.error-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-apm.internal-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-apm.profiling-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - traces-apm.rum-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - traces-apm.sampled-default
          privileges:
            - auto_configure
            - create_doc
            - maintenance
            - monitor
            - read
        - names:
            - traces-apm-default
          privileges:
            - auto_configure
            - create_doc
      cluster:
        - 'cluster:monitor/main'
agent:
  download:
    source_uri: 'https://artifacts.elastic.co/downloads/'
  monitoring:
    enabled: true
    use_output: default
    namespace: default
    logs: true
    metrics: true
inputs:
  - id: apm
    name: apm-1
    revision: 1
    type: apm
    use_output: default
    meta:
      package:
        name: apm
        version: 8.4.2
    data_stream:
      namespace: default
    apm-server:
      auth:
        anonymous:
          enabled: true
          allow_agent:
            - rum-js
            - js-base
            - iOS/swift
          allow_service: null
          rate_limit:
            event_limit: 300
            ip_limit: 1000
        api_key:
          enabled: false
          limit: 100
        secret_token: null
      capture_personal_data: true
      idle_timeout: 45s
      default_service_environment: null
      expvar.enabled: false
      pprof.enabled: false
      host: 'localhost:8200'
      max_connections: 0
      max_event_size: 307200
      max_header_size: 1048576
      read_timeout: 3600s
      response_headers: null
      java_attacher:
        enabled: false
        discovery-rules: null
        download-agent-version: null
      rum:
        enabled: true
        allow_headers: null
        allow_origins:
          - '*'
        exclude_from_grouping: ^/webpack
        library_pattern: node_modules|bower_components|~
        response_headers: null
      shutdown_timeout: 30s
      ssl:
        enabled: false
        certificate: null
        key: null
        key_passphrase: null
        supported_protocols:
          - TLSv1.1
          - TLSv1.2
          - TLSv1.3
        cipher_suites: null
        curve_types: null
      write_timeout: 30s
      sampling:
        tail:
          enabled: false
          interval: 1m
          policies:
            - sample_rate: 0.1
          storage_limit: 3GB

#---------------------------- Logstash output -----------------------------
# no!!!APM send so metrics
#output.logstash:
#  enabled: true
#  hosts: ["logstash.${APP_HOST}.${APP_NET}:5044"]
#  #protocol: "https"
#  #username: "apm_system"
#  username: "${ELASTICSEARCH_USERNAME}"
#  password: "${ELASTICSEARCH_PASSWORD}"

#=============================== HTTP Endpoint ===============================

http.enabled: true
http.host: "0.0.0.0"
#http.host: "apm.nginx.local"
http.port: 5066

#============================= X-pack Monitoring =============================

xpack.monitoring.enabled: true
monitoring:
  enabled: false
  cluster_uuid: "${CLUSTER_UUID}"

# monitoring.elasticsearch:
#   username: "${ELASTICSEARCH_USERNAME}"
#   password: "${ELASTICSEARCH_PASSWORD}"
#   hosts: 
#     - "https://es01.${APP_HOST}.${APP_NET}:9200"
#     - "https://es02.${APP_HOST}.${APP_NET}:9201"
#     # - "https://es03.${APP_HOST}.${APP_NET}:9202"
#   protocol: "https"
#   ssl.enabled: true
#   ssl.certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
#   ssl.verification_mode: "certificate"
#   ssl.certificate: "${APM_SERVER_CERT}"
#   ssl.key: "${APM_SERVER_CERT_KEY}"
