# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: ["lhsdock-apm:5066", "lhsdock-metric:5066", "lhsdock-file:5066", "lhsdock-heart:5066"]
  username: "beats_system"
  password: "${ELASTICSEARCH_PASSWORD}"
  # ssl:
  #  enabled: true
  #  certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
