# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: ["apm.nginx.local:5066", "metric.nginx.local:5067", "file.nginx.local:5068", "heart.nginx.local:5069"]
  username: "beats_system"
  password: "${ELASTICSEARCH_PASSWORD}"
  # ssl:
  #  enabled: true
  #  certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
