# Module: logstash
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-logstash.html

- module: logstash
  #metricsets:
  #  - node
  #  - node_stats
  period: 10s
  hosts: ["logstash:9600"]
  username: "logstash_system"
  password: "${ELASTICSEARCH_PASSWORD}"
