# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-nginx.html

- module: nginx
  # metricsets:
  #  - stubstatus
  period: 10s

  # Nginx hosts
  # hosts: ["http://wiki.docker.nginx.local", "http://www.wordpress.local", "http://docker.wordpress.local"]
  hosts: ["http://docker.nginx.local", "http://wiki.docker.nginx.local", "http://docker.tomcat.local"]

  # Path to server status. Default nginx_status
  #server_status_path: "nginx_status"

  #username: "user"
  #password: "secret"
  ssl:
    enabled: true
    certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
